import React from "react";
import { 
  Code2, 
  Terminal, 
  Database, 
  Smartphone, 
  Globe, 
  Server, 
  Palette, 
  Layers, 
  Cpu, 
  Cloud, 
  Lock, 
  Settings, 
  Layout, 
  Tv, 
  Flame, 
  Zap, 
  GitBranch, 
  Shield, 
  Tag, 
  ToggleLeft, 
  Briefcase,
  Box,
  FileCode,
  FileText,
  Folder,
  HardDrive,
  Hash,
  Image,
  Key,
  Link2,
  Monitor,
  Network,
  Radio,
  Rss,
  Search,
  Share2,
  ShieldAlert,
  ShoppingCart,
  Sliders,
  Sparkles,
  Star,
  Target,
  Users,
  Video,
  Wifi,
  Wrench,
  BookOpen,
  Compass,
  Activity,
  Play,
  Send,
  Mail
} from "lucide-react";

export const iconMap: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  Code2, 
  Terminal, 
  Database, 
  Smartphone, 
  Globe, 
  Server, 
  Palette, 
  Layers, 
  Cpu, 
  Cloud, 
  Lock, 
  Settings, 
  Layout, 
  Tv, 
  Flame, 
  Zap, 
  GitBranch, 
  Shield, 
  Tag, 
  ToggleLeft, 
  Briefcase,
  Box,
  FileCode,
  FileText,
  Folder,
  HardDrive,
  Hash,
  Image,
  Key,
  Link2,
  Monitor,
  Network,
  Radio,
  Rss,
  Search,
  Share2,
  ShieldAlert,
  ShoppingCart,
  Sliders,
  Sparkles,
  Star,
  Target,
  Users,
  Video,
  Wifi,
  Wrench,
  BookOpen,
  Compass,
  Activity,
  Play,
  Send,
  Mail
};

export const devicons: Record<string, string> = {
  "Laravel": "devicon-laravel-original",
  "Next.js": "devicon-nextjs-plain",
  "NestJS": "devicon-nestjs-plain",
  "PHP": "devicon-php-plain",
  "JavaScript": "devicon-javascript-plain",
  "TypeScript": "devicon-typescript-plain",
  "Kotlin": "devicon-kotlin-plain",
  "Ionic": "devicon-ionic-original",
  "React": "devicon-react-original",
  "Vue.js": "devicon-vuejs-plain",
  "Angular": "devicon-angularjs-plain",
  "Node.js": "devicon-nodejs-plain",
  "Tailwind CSS": "devicon-tailwindcss-original",
  "Prisma": "devicon-prisma-original",
  "MySQL": "devicon-mysql-plain",
  "PostgreSQL": "devicon-postgresql-plain",
  "SQLite": "devicon-sqlite-plain",
  "MongoDB": "devicon-mongodb-plain",
  "Redis": "devicon-redis-plain",
  "Firebase": "devicon-firebase-plain",
  "Supabase": "devicon-supabase-plain",
  "GraphQL": "devicon-graphql-plain",
  "Docker": "devicon-docker-plain",
  "Kubernetes": "devicon-kubernetes-plain",
  "Git": "devicon-git-plain",
  "GitHub": "devicon-github-original",
  "AWS": "devicon-aws-plain",
  "Java": "devicon-java-plain",
  "Python": "devicon-python-plain",
  "Go": "devicon-go-plain",
  "Rust": "devicon-rust-original",
  "C#": "devicon-csharp-plain",
  "C++": "devicon-cplusplus-plain",
  "Ruby": "devicon-ruby-plain",
  "Swift": "devicon-swift-plain",
  "Flutter": "devicon-flutter-plain",
  "Android": "devicon-android-plain",
  "Apple": "devicon-apple-original",
  "Linux": "devicon-linux-plain",
  "HTML5": "devicon-html5-plain",
  "CSS3": "devicon-css3-plain",
  "Sass": "devicon-sass-original",
  "Bootstrap": "devicon-bootstrap-plain",
  "npm": "devicon-npm-original-wordmark",
  "Yarn": "devicon-yarn-plain",
  "Vite": "devicon-vite-original",
  "Webpack": "devicon-webpack-plain",
  "VS Code": "devicon-vscode-plain",
  "Figma": "devicon-figma-plain",
  "Django": "devicon-django-plain",
  "Spring Boot": "devicon-spring-original",
  "Jenkins": "devicon-jenkins-line",
};
